CREATE TABLE IF NOT EXISTS firmas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id VARCHAR(255),
    correo VARCHAR(255),
    estado VARCHAR(255),
    respuesta_signio VARCHAR(5000),
    fecha_creacion TIMESTAMP,
    fecha_actualizacion TIMESTAMP,
    usuario_creacion VARCHAR(255),
    usuario_actualizacion VARCHAR(255)
);
