CREATE TABLE IF NOT EXISTS firma_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_id BIGINT,
    proveedor VARCHAR(255),
    id_evento_externo VARCHAR(255),
    id_transaccion_externa VARCHAR(255),
    documento_id VARCHAR(255),
    estado_externo VARCHAR(255),
    estado_anterior VARCHAR(255),
    estado_nuevo VARCHAR(255),
    mensaje VARCHAR(1000),
    fecha_evento TIMESTAMP,
    fecha_recepcion TIMESTAMP,
    CONSTRAINT fk_firma_eventos_firma
        FOREIGN KEY (firma_id)
        REFERENCES firmas(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_firma_evento_proveedor_evento
    ON firma_eventos(proveedor, id_evento_externo);
